source 'https://github.com/CocoaPods/Specs.git'

target 'LXBoardGameGeek', :exclusive => true do
  pod "LXBoardGameGeek", :path => "../"
  pod "XMLDictionary", '~> 1.4'
end

target 'Tests', :exclusive => true do
  pod "LXBoardGameGeek", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
